const reviews = [
  // ---------- Shirt 1 ---------- 
  {
    id: 'cl004kg800045l4vi49adng05',
    name: 'Alan Ross',
    email: 'AlanRoss@gmail.com',
    content: 'My neighbor Eller has one of these. She works as a butler and she says it looks amazing.',
    rating: 5,
    productId: 'ckzywzytm00413svi6jezdk1o',
    approved: true,
  },
  {
    id: '7yhhsl824o491zfcmn3zaqk2o',
    name: 'Isaiah Simmmons',
    email: 'IsaiahSimmmons@gmail.com',
    content: 'Fits perfectly',
    rating: 4.7,
    productId: 'ckzywzytm00413svi6jezdk1o',
    approved: true,
  },
  {
    id: '9smholyoukndhyjcw7bs9f5hi',
    name: 'Eugene Jordan',
    email: 'EugeneJordan@gmail.com',
    content: 'A little bit small in the sholded, but ima pretty big guy',
    rating: 4,
    productId: 'ckzywzytm00413svi6jezdk1o',
    approved: true,
  },
  // ---------- Shirt 2 ---------- 
  {
    id: 'fbi4jhz1otneb02gskhuong05',
    name: 'Beth George',
    email: 'BethGeorge@gmail.com',
    content: 'Nice color, but I find the fabric a bit itchy',
    rating: 3,
    productId: 'cl00ep6zb0005eovi5oym6d8o',
    approved: true,
  },
  {
    id: '1l2mnqscw6b9n3ucnwvfmenx0',
    name: 'Harbert Gerardet',
    email: 'HarbertGerardet@gmail.com',
    content: 'Fantastic!',
    rating: 4.7,
    productId: 'cl00ep6zb0005eovi5oym6d8o',
    approved: true,
  },
  {
    id: 'ayrenepjxdfpk58ir1o1gk0lb',
    name: 'Savannah Curtis',
    email: 'SavannahCurtis@gmail.com',
    content: 'Gave it to my brother as a gift he loves it',
    rating: 4,
    productId: 'cl00ep6zb0005eovi5oym6d8o',
    approved: true,
  },
  {
    id: 'wfs6ftrtfl39upoz2nvm2lkvb',
    name: 'Charlie Gregory',
    email: 'CharlieGregory@gmail.com',
    content: 'Nice! Would buy another.',
    rating: 4.6,
    productId: 'cl00ep6zb0005eovi5oym6d8o',
    approved: true,
  },
  {
    id: 'omswgdrs2uvwb6ueh339f4ugp',
    name: 'Leah Ford',
    email: 'LeahFord@gmail.com',
    content: 'Happy with my purchace',
    rating: 3.9,
    productId: 'cl00ep6zb0005eovi5oym6d8o',
    approved: true,
  },
  // ---------- Shirt 3 ---------- 
  {
    id: 'jke592ev6t78tc6i3eckc1ht5',
    name: 'Kevin Berry',
    email: 'KevinBerry@gmail.com',
    content: 'My new favourite shirt',
    rating: 4.5,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  {
    id: 'eq6kkeaj0mm0n6te4tzn4twf3',
    name: 'Clayton Thompson',
    email: 'ClaytonThompson@gmail.com',
    content: 'Slow delivery, but okay quality',
    rating: 2,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  {
    id: '16c5zca86v5dqc54j2t8ekg9s',
    name: 'Philip Cruz',
    email: 'PhilipCruz@gmail.com',
    content: 'Doesnt fit at all',
    rating: 1,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  {
    id: '2el3ssercwk4hiki5vndoprcx',
    name: 'Victor Rose',
    email: 'VictorRose@gmail.com',
    content: 'Fits perfectly',
    rating: 5,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  {
    id: 'm5bvawllx94hcnek7wlji9eyu',
    name: 'Zack Scott',
    email: 'ZackScott@gmail.com',
    content: 'Fast delivery, happy with my purchase',
    rating: 4.5,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  {
    id: '3trdmut6h1e243yoswlnqujjq',
    name: 'Ray Hicks',
    email: 'RayHicks@gmail.com',
    content: 'Good quality shirt',
    rating: 4,
    productId: 'cl00195lv00658gviriq5udt2',
    approved: true,
  },
  // ---------- Pant 1 ---------- 
  {
    id: '6mrifz3zlklk4al016srjsy07',
    name: 'Sandra Sutton',
    email: 'SandraSutton@gamil.com',
    content: 'OMG I just love these pants they fire!',
    rating: 4.8,
    productId: 'ckzyxktb501843sviv5w8g39i',
    approved: true,
  },
  {
    id: 'bmpbdhpm5wsxi3ntzsjlkohii',
    name: 'Jo Coleman',
    email: 'JoColeman@gamil.com',
    content: 'Really cool',
    rating: 4,
    productId: 'ckzyxktb501843sviv5w8g39i',
    approved: true,
  },
  {
    id: '3r1fpn2jthimyh6jju7ojsy07',
    name: 'Jean Barrett',
    email: 'JeanBarrett@gamil.com',
    content: 'Fast and good quality',
    rating: 4.8,
    productId: 'ckzyxktb501843sviv5w8g39i',
    approved: true,
  },
  {
    id: 'byvxigfmmr0rzdhery1uaww06',
    name: 'Randall Hicks',
    email: 'RandallHicks@gamil.com',
    content: 'I dont feel comfrtable when I wear these in public',
    rating: 1.8,
    productId: 'ckzyxktb501843sviv5w8g39i',
    approved: true,
  },
  {
    id: '27hqs3r0whljywny1aoqti1av',
    name: 'Reginald Kelley',
    email: 'ReginaldKelley@gamil.com',
    content: 'My girlfriend loves them',
    rating: 5,
    productId: 'ckzyxktb501843sviv5w8g39i',
    approved: true,
  },
  // ---------- Pant 2 ---------- 
  {
    id: '27hqspe21tl1rvgj3v283lzm8',
    name: 'Oliver	Fassman',
    email: 'OliverFassman@gmail.com',
    content: 'Swagger',
    rating: 4.1,
    productId: 'ckzzbq1nf000524vi1s1yeeuz',
    approved: true,
  },
  {
    id: 'y1ljft51qcvmydv6yoods3pqu',
    name: 'Caspar Lakey',
    email: 'CasparLakey@gmail.com',
    content: 'Happy would reccomend',
    rating: 4.5,
    productId: 'ckzzbq1nf000524vi1s1yeeuz',
    approved: true,
  },
  {
    id: 'bsfhrqungi4bkwqpbhemyp4qy',
    name: 'Norean	Papaccio',
    email: 'NoreanPapaccio@gmail.com',
    content: 'Great pants look cool',
    rating: 5,
    productId: 'ckzzbq1nf000524vi1s1yeeuz',
    approved: true,
  },
  {
    id: 'pd5zsqa4opq8smwddwiurwdia',
    name: 'Leslie	Metzig',
    email: 'LeslieMetzig@gmail.com',
    content: 'I feel really cool when I wear these, I also bought the jacket to match!',
    rating: 4.3,
    productId: 'ckzzbq1nf000524vi1s1yeeuz',
    approved: true,
  },
  // ---------- Pant 3 ---------- 
  {
    id: 'h3pvly9biz23s2a9ek1n74gkf',
    name: 'Zack	Pitcher',
    email: 'ZackPitcher@gmail.com',
    content: 'Proffessional look, good for work',
    rating: 5,
    productId: 'ckzyxh6of01453svii3bxf707',
    approved: true,
  },
  {
    id: 'rplhea9fvix37rk1o89keuikq',
    name: 'Stephie Frangleton',
    email: 'StephieFrangleton@gmail.com',
    content: 'Really good fit',
    rating: 4.5,
    productId: 'ckzyxh6of01453svii3bxf707',
    approved: true,
  },

]

module.exports = {reviews}