import React from 'react'
import Head from 'next/head'
import NextLink from 'next/link'
import { AppBar, Toolbar, Typography, Container, Link } from '@mui/material'

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Ecom Template | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static" className="bg-[#203040] text-[#ffffff]">
        <Toolbar>
          <NextLink href="/" passHref>
            <a className='text-2xl bold font-bold hover:text-gray-200'>
              Ecom Template
            </a>
          </NextLink>
          <div className='ml-auto space-x-4'>
            <NextLink href="/cart" passHref>
              <a className='hover:text-gray-200'>
                Cart
              </a>
            </NextLink>
            <NextLink href="/login" passHref>
              <a className='hover:text-gray-200'>
                Login
              </a>
            </NextLink>
          </div>
        </Toolbar>
      </AppBar>

      <Container className="h-[80vh]">
        {children}
      </Container>

      <footer className="text-center">
        <Typography>All rights reserved. Ecom Template</Typography>
      </footer>
    </div>
  )
}