import React from 'react'
import Head from 'next/head'
import { AppBar, Toolbar, Typography, Container } from '@mui/material'

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Ecom Template | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="static" className="bg-[#203040] text-[#ffffff]">
        <Toolbar>
          <Typography>Ecom Template</Typography>
        </Toolbar>
      </AppBar>

      <Container className="h-[80vh]">
        {children}
      </Container>

      <footer className="text-center">
        <Typography>All rights reserved. Ecom Template</Typography>
      </footer>
    </div>
  )
}