export const data = {
  products: [
    {
      name: 'Mens Regular Fit Oxford Cotton Shirt',
      category: 'Shirts',
      image: '/images/shirts/shirt1/1.avif',
      brand: 'Lacrosse ',
      description: 'Made in compact Oxford cotton authentic and durable, this shirt softens and becomes softer with each wash. This solid-coloured shirt has it all: a classic button-down collar, a patch pocket on the chest, and real mother-of-pearl buttons. Its available in several contemporary pastel colours and will look great with a V-neck sweater and raw rolled-up jeans.',
      price: 90,
      rating: 4.5,
      numReviews: 10,
      numInStock: 11,
    },
    {
      name: 'Mens Regular Fit Premium Cotton Shirt',
      category: 'Shirts',
      image: '/images/shirts/shirt2/1.avif',
      brand: 'Lacrosse',
      description: 'Pure, clean lines define this shirt which is available in 7 modern colours. Made in a high-end honeycombed fabric, a casual wash is applied for Lacoste sportswear DNA. It is embellished with genuine mother-of-pearl buttons and an iconic small green embroidered crocodile on the chest. Designed in the spirit of the iconic Lacoste piqué, this new essential is the perfect addition to your seasonal wardrobe.',
      price: 70,
      rating: 3.5,
      numReviews: 6,
      numInStock: 4,
    },
    {
      name: 'Mens Regular Fit Oxford Cotton Shirt',
      category: 'Shirts',
      image: '/images/shirts/shirt3/1.avif',
      brand: 'Lacrosse',
      description: 'Made from high-quality Oxford cotton, this tailored shirt will be a stylish addition to your wardrobe. Elegant and comfortable, it is embellished with real mother-of-pearl buttons and features a rounded hem and a chest pocket. This cant-miss seasonal classic will look great with all your bottoms.',
      price: 90,
      rating: 3.5,
      numReviews: 6,
      numInStock: 4,
    },
    {
      name: 'Mens Lacoste SPORT Lettered Bands Lightweight Tracksuit Pants',
      category: 'Pants',
      image: '/images/pants/pants1/1.avif',
      brand: 'Lacrosse',
      description: 'Step up with the athletic, high-performance allure of these signature tracksuit pants. Crafted in lightweight diamond taffeta and lined in soft jersey, they are equipped with an elasticised waistband, zip leg bottoms and concealed pockets. A Lacoste-lettered contrast band completes this trendy sport-infused look.',
      price: 90,
      rating: 4.2,
      numReviews: 135,
      numInStock: 30,
    },
    {
      name: 'Mens Lacoste SPORT Colour-block Bands Tracktrousers',
      category: 'Pants',
      image: '/images/pants/pants2/1.avif',
      brand: 'Lacrosse',
      description: 'A colour-block band adorned with an oversized crocodile brings a striking touch to these Lacoste Sport tracktrousers. Made of a lightweight diamond and recycled woven material, the piece is equipped with practical pockets but also an elasticised waistband and ankles. Its athletic allure and perfect comfort puts you in the lead on all grounds.',
      price: 110,
      rating: 5,
      numReviews: 2,
      numInStock: 10,
    },
    {
      name: 'Mens Slim Fit Stretch Gabardine Chino Pants',
      category: 'Pants',
      image: '/images/pants/pants3/1.avif',
      brand: 'Lacrosse',
      description: 'Slim crafting in stretch gabardine with side pockets, these chino pants are an elegant take on a classic. Perfect with sneakers and a short-sleeved shirt.',
      price: 90,
      rating: 4.7,
      numReviews: 2,
      numInStock: 10,
    }
  ]
}