import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecom Template | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Ecom Template</h1>
      </main>


    </>
  )
}
